### ISSUE TITLE
Just want a small help

### ISSUE THREAD

**Issue by PradumTiwari** [Sachin-RJ7/JS-Backend#1]
hii bro can you give me discord link of sanket singh backend course as i havent get the link 
It will be a huge help

**Comment by Sachin-RJ7** [comment]
Brother, only one person can join from the link and now I have no links,
they also got expired

**Comment by PradumTiwari** [comment]
It is ok brother can you send me all the notes of his course will be greatful to you

**Comment by Sachin-RJ7** [comment]
Send me your discord id or discord link,  I will send you and one question
is that where from you got my gmail id???

**Comment by PradumTiwari** [comment]
Sorry for the Late response I was having some health issue and thanks for your help my username is .pradumkumar
